#pragma once
#include <stddef.h>
#include <stdint.h>
#include <Homography.h>

// Generated by tools/calibrate.py. Review before installing.
// Provenance: synthetic; NOT hardware validated.
// CALIBRATION_CONFIRMED stays false even when numerical holdout passes.
namespace sorter_calibration {
constexpr uint32_t CALIBRATION_ID = 3358441978u;
constexpr bool CALIBRATION_CONFIRMED = false;
constexpr uint16_t IMAGE_WIDTH = 320;
constexpr uint16_t IMAGE_HEIGHT = 240;
constexpr double HOMOGRAPHY[9] = {0.42001015674577852, 0.025006883765973442, -69.991375755773461, 0.014963125174115282, 0.40007901452184458, 55.001408278359222, 0.00060051827141025752, -0.00039999016262483355, 1};
constexpr size_t SUPPORT_COUNT = 4;
const sorter::Point2 SUPPORT[SUPPORT_COUNT] = {
    {30, 25},
    {290, 25},
    {290, 215},
    {30, 215},
};
}  // namespace sorter_calibration
